// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvcbgoatolxgyuyuqyyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2Y2Jnb2F0b2x4Z3l1eXVxeXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTI3OTgsImV4cCI6MjA2MjEyODc5OH0.KJUPTqJX3of7XWZVogkg0kVHY2c2ftG5boi55GiZlRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);